### ISSUE TITLE
Simple typo in doc

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [GDGToulouse/devfest-embedded-devices-monorepo#60]
# Bug report

## Description

Just found a typo in docs

## To Reproduce

1. Go to https://github.com/GDGToulouse/devfest-embedded-devices-monorepo/blob/master/docs/miscellaneous/epitech-project-description.md#organisation-and-tools
2. see `[...] will be drived [...]`

## Environment

github in the browser

So instead of `[...] will be drived [...]`, should be `[...] will be driven [...]` :  the non french-speaking reader will then no llonger be dsimayed reading the docs.

And also there to tell you that I liked the spirit of the initiative : an idea , and we play with all we can find in our gigantic open source world.

You should try and go the step beyond.

**Comment by hadrien-toma** [comment]
Hello @Jean-Baptiste-Lasselle, thank you for raising this issue and for the kind words, may I ask you to propose a merge request ?

**Comment by Jean-Baptiste-Lasselle** [comment]
> Hello @Jean-Baptiste-Lasselle, thank you for raising this issue and for the kind words, may I ask you to propose a merge request ?

Hi @hadrien-toma, you certainly may, as well as I do appreciate that you ask. 

Now done :  I am more acquianted with Gitlab merge requests, do not hesitate to ping me if I have to reboot the pull request with your requirements

**Comment by hadrien-toma** [comment]
It is merged, thank you very much!
