### ISSUE TITLE
Do OpenMV camera can obstacle avoidance and find way like Lidar or sonic sensor? any camera do that?

### ISSUE THREAD

**Issue by shoaibsayed1** [GDGToulouse/devfest-embedded-devices-monorepo#62]
Do OpenMV camera can obstacle avoidance and find way like Lidar or sonic sensor? does any camera can do that?
my graduation project is about obstacle detection and find way to search fire and identify different object. I have sonic sensor and professor want something image base which can detect any object and situation and find his own way to travel more.
I have raspberry pi 4 model b.

**Comment by hadrien-toma** [comment]
Hello @shoaibsayed1, this is not a use case we are targeting for the moment. Good luck for your project.
